In [3]:
import numpy as np # type: ignore

from payment_simulator import GroupedPaymentNetwork, SimplePaymentNetwork

In [7]:
init_banks = 3
increment = 4
total_banks = 9
alpha = 0.00001
avg_payments = 1000
allow_self_loop = False


In [8]:
network = SimplePaymentNetwork(
    total_banks=total_banks,
    avg_payments=avg_payments,
    alpha=alpha,
    allow_self_loop=allow_self_loop,
)
network.simulate_payments(increment=increment, init_banks=init_banks)


In [9]:
print("Bank strengths:")
print(network.h)

print("Network links:")
print(np.round(network.extract_link_matrix(), 4))
print(network.extract_link_matrix(False).sum() == total_banks * avg_payments)

Bank strengths:
[1.03852 1.03829 1.03784 1.01872 1.01337 1.01351 1.01305 1.0045  1.0022 ]
Network links:
[[0.     0.0813 0.0752 0.0199 0.013  0.0116 0.0116 0.0033 0.0014]
 [0.075  0.     0.0726 0.0226 0.0113 0.0112 0.009  0.003  0.0018]
 [0.0731 0.0777 0.     0.0199 0.0118 0.0101 0.0121 0.0037 0.0017]
 [0.0212 0.0207 0.0219 0.     0.0127 0.0096 0.0124 0.0034 0.0016]
 [0.0099 0.0126 0.0131 0.0117 0.     0.0123 0.0098 0.0027 0.001 ]
 [0.0131 0.0118 0.0113 0.0134 0.011  0.     0.0107 0.0033 0.0023]
 [0.0136 0.0094 0.0109 0.0111 0.012  0.0133 0.     0.003  0.0018]
 [0.0031 0.0039 0.0038 0.0047 0.0026 0.0036 0.0032 0.     0.0012]
 [0.0017 0.0017 0.0017 0.0013 0.0012 0.0014 0.0011 0.0016 0.    ]]
True


In [10]:
g_network = GroupedPaymentNetwork(
    total_banks=324,
    bank_groups=[15, 25, 30, 30],
    avg_payments=213,
    alpha=0.01,
    allow_self_loop=False,
)
g_network.simulate_payments(increment=25, init_banks=5)

In [11]:
print("Network links:")
print(324 * 213)
print(g_network.extract_link_matrix(False).sum())

Network links:
69012
69012.0
